### ISSUE TITLE
"string indices must be integers" error

### ISSUE THREAD

**Issue by npotternyc** [singer-io/tap-urban-airship#5]
Is anyones else seeing this? This started happening a couple of days ago when the data is uploaded to the stitch API:

```2018-06-26 12:55:10,428Z   main - INFO Running tap-urban-airship version 0.8.1 and target-stitch version 1.7.4
2018-06-26 12:55:10,537Z   main - DEBUG Getting initial state
2018-06-26 12:55:10,582Z   main - INFO Starting tap: tap-env/bin/tap-urban-airship --config /tmp/tap_config.json --state /tmp/tap_state.json
2018-06-26 12:55:10,585Z   main - INFO Starting target: target-env/bin/target-stitch --config /tmp/target_config.json
2018-06-26 12:55:10,801Z    tap -   INFO Starting sync
2018-06-26 12:55:10,806Z    tap -   INFO GET https://go.urbanairship.com/api/lists
2018-06-26 12:55:10,867Z    tap -   INFO GET https://go.urbanairship.com/api/channels
2018-06-26 12:55:10,987Z target - INFO Using Stitch import URL https://api.stitchdata.com/v2/import/batch
2018-06-26 12:55:10,987Z   main - INFO State update: adding lists = "2017-10-01T04:00:00Z"
2018-06-26 12:55:10,988Z   main - DEBUG Saving state: {'lists': '2017-10-01T04:00:00Z'}
2018-06-26 12:55:12,821Z    tap - CRITICAL string indices must be integers
2018-06-26 12:55:12,822Z    tap - Traceback (most recent call last):
2018-06-26 12:55:12,823Z    tap -   File "tap-env/bin/tap-urban-airship", line 11, in <module>
2018-06-26 12:55:12,823Z    tap -     sys.exit(main())
2018-06-26 12:55:12,823Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_urban_airship/__init__.py", line 136, in main
2018-06-26 12:55:12,823Z    tap -     raise exc
2018-06-26 12:55:12,823Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_urban_airship/__init__.py", line 133, in main
2018-06-26 12:55:12,823Z    tap -     main_impl()
2018-06-26 12:55:12,823Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_urban_airship/__init__.py", line 129, in main_impl
2018-06-26 12:55:12,823Z    tap -     do_sync()
2018-06-26 12:55:12,823Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_urban_airship/__init__.py", line 106, in do_sync
2018-06-26 12:55:12,823Z    tap -     sync_entity("channels", ["channel_id"], ["created", "last_registration"])
2018-06-26 12:55:12,824Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_urban_airship/__init__.py", line 87, in sync_entity
2018-06-26 12:55:12,824Z    tap -     row = transform_row(row, schema)
2018-06-26 12:55:12,824Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_urban_airship/transform.py", line 6, in transform_row
2018-06-26 12:55:12,824Z    tap -     return _transform_field(row, schema)
2018-06-26 12:55:12,824Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_urban_airship/transform.py", line 79, in _transform_field
2018-06-26 12:55:12,824Z    tap -     return _object(value, field_schema["properties"])
2018-06-26 12:55:12,824Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_urban_airship/transform.py", line 29, in _object
2018-06-26 12:55:12,824Z    tap -     for field, field_schema in properties_schema.items()
2018-06-26 12:55:12,824Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_urban_airship/transform.py", line 30, in <dictcomp>
2018-06-26 12:55:12,824Z    tap -     if field in data}
2018-06-26 12:55:12,824Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_urban_airship/transform.py", line 76, in _transform_field
2018-06-26 12:55:12,825Z    tap -     return _array(value, field_schema["items"])
2018-06-26 12:55:12,825Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_urban_airship/transform.py", line 24, in _array
2018-06-26 12:55:12,825Z    tap -     return [_transform_field(value, items_schema) for value in data]
2018-06-26 12:55:12,825Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_urban_airship/transform.py", line 24, in <listcomp>
2018-06-26 12:55:12,825Z    tap -     return [_transform_field(value, items_schema) for value in data]
2018-06-26 12:55:12,825Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_urban_airship/transform.py", line 79, in _transform_field
2018-06-26 12:55:12,825Z    tap -     return _object(value, field_schema["properties"])
2018-06-26 12:55:12,825Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_urban_airship/transform.py", line 29, in _object
2018-06-26 12:55:12,825Z    tap -     for field, field_schema in properties_schema.items()
2018-06-26 12:55:12,826Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_urban_airship/transform.py", line 30, in <dictcomp>
2018-06-26 12:55:12,826Z    tap -     if field in data}
2018-06-26 12:55:12,826Z    tap - TypeError: string indices must be integers
2018-06-26 12:55:12,845Z target - INFO Sending batch with 18 messages for table channels to https://api.stitchdata.com/v2/import/batch
2018-06-26 12:55:12,963Z target - INFO Exiting normally
2018-06-26 12:55:13,002Z   main - INFO Target exited normally with status 0
2018-06-26 12:55:13,003Z   main - INFO Exit status is: Check failed with code None. Discovery failed with code None. Tap failed with code 1 and error message: "string indices must be integers". Target succeeded.```

**Comment by briansloane** [comment]
The data from the API may have changed and the tap is now getting a string when it is expecting a dict. I would recommend trying to reproduce this locally by running the tap in your development environment.

**Comment by npotternyc** [comment]
@briansloane Can we get this merged?
